### ISSUE TITLE
Migrate datahub to new machine

### ISSUE THREAD

**Issue by rgrp** [okfn/ckanext-datahub#46]
Move to hydrogen.okfnlabs.org

## Questions

* How do we do deployment?
  * docker - https://index.docker.io/u/kindly/ckan_base/
  * ansible - https://github.com/goabout/ansible-datahub
  * ... ?
* What do we need to backup and how?
  * Database (metadata) - Yes
  * Database (DataStore) - ??
  * Storage (google storage) - No (since GS is replicated itself)
* Monitoring
* Database and webapp on separate machine? (or in separate docker instances??)
  * ??

**Comment by pwalsh** [comment]
Is now on a new OKFN machine.
