### ISSUE TITLE
Upgrade to 2.3

### ISSUE THREAD

**Issue by rossjones** [okfn/ckanext-datahub#73]
What do we need to do to upgrade to 2.3, what breaks..

## Todo 

* [ ] Make sure all resources have a default preview (if they're of a type where a preview exists)

## Broken

* [ ] Homepage looks funny, probably template changes.

**Comment by rgrp** [comment]
@rossjones do we need to sort storage?

Huge +1 on getting to v2.3!

**Comment by pwalsh** [comment]
Now on 2.4
